name:                bihashmap
version:             0.1.0.0
github:              "ix/bihashmap"
license:             BSD3
author:              "Rose &quot;ix&quot;"
maintainer:          "rose@empty.town"
copyright:           "Rose 2019"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ix/bihashmap#readme>

dependencies:
- base                 >= 4.12.0 && < 4.13
- hashable             >= 1.2.7.0 && < 1.4
- unordered-containers >= 0.2.10 && < 0.3
- deepseq              >= 1.4.4 && < 1.5

library:
  source-dirs: src

tests:
  bihashmap-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec >= 2.7.1 && < 2.8
    - bihashmap
